-- 0013_narrative_timeline.sql
-- Autobiographical narrative entries produced by the Narrative Weaver (Block 4).

CREATE TABLE IF NOT EXISTS narrative_timeline (
    id                  INTEGER PRIMARY KEY AUTOINCREMENT,
    period_label        TEXT NOT NULL,        -- concrete lowercase label, e.g. "the week teo went quiet"
    what_happened       TEXT NOT NULL,
    what_shifted        TEXT NOT NULL DEFAULT '',
    still_sitting_with  TEXT NOT NULL DEFAULT '',
    felt_texture        TEXT NOT NULL DEFAULT '',
    chapter_transition  BOOLEAN NOT NULL DEFAULT 0,
    week_start          TEXT NOT NULL,        -- ISO date of Monday that week started
    created_at          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_narrative_created ON narrative_timeline(created_at DESC);

-- Character addenda: relational snapshots generated by Narrative Weaver on
-- chapter_transition or every 30 days.
CREATE TABLE IF NOT EXISTS character_addenda (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    person_id   INTEGER REFERENCES persons(id),   -- NULL = generic
    body        TEXT NOT NULL,
    version     INTEGER NOT NULL DEFAULT 1,
    archived    BOOLEAN NOT NULL DEFAULT 0,
    created_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_addenda_person ON character_addenda(person_id, archived);
