"""Character addendum system — relational snapshot in Chloe's voice.

Generated by the Narrative Weaver when chapter_transition=True or every 30 days.
Describes how Chloe currently talks to a specific person: what she assumes,
what she's stopped explaining, what she does differently.

Stored in character_addenda table. Injected into chat prompt after static prefix.
"""
from __future__ import annotations

from chloe.observability.logging import get_logger
from chloe.state.db import get_connection

log = get_logger("identity.character_addendum")


async def update_addendum(
    person_id: int | None = None,
    narrative_context: str = "",
) -> str | None:
    """Generate and store a new character addendum via Flash call.

    Returns the addendum text, or None on failure.
    """
    from chloe.llm.gemini import GeminiClient
    from pydantic import BaseModel, Field

    class AddendumOutput(BaseModel):
        addendum: str = Field(max_length=1000)

    conn = get_connection()
    from chloe.identity.aesthetics import load_patterns_for_addendum
    aesthetic_patterns = load_patterns_for_addendum()

    payload = {
        "person_name": _person_name(conn, person_id),
        "narrative_context": narrative_context[:500],
        "recent_interactions": _recent_interactions(conn, person_id),
        "trait_state": _trait_state(conn),
        "aesthetic_patterns": aesthetic_patterns or "(none yet)",
    }

    client = GeminiClient()
    result = await client.flash("character_addendum.md", payload, AddendumOutput)

    if not result:
        log.warning("addendum_llm_returned_none")
        return None

    body = (result.get("addendum") if isinstance(result, dict) else getattr(result, "addendum", "")) or ""
    body = body.strip()[:1000]
    if not body:
        return None

    # Archive previous addendum for this person
    conn.execute(
        "UPDATE character_addenda SET archived=1 WHERE person_id IS ? AND archived=0",
        (person_id,),
    )
    conn.execute(
        "INSERT INTO character_addenda (person_id, body) VALUES (?, ?)",
        (person_id, body),
    )
    conn.commit()
    log.info("addendum_written", person_id=person_id, length=len(body))
    return body


def load_addendum(person_id: int | None = None) -> str:
    """Return the active character addendum for a person (empty string if none)."""
    try:
        conn = get_connection()
        row = conn.execute(
            "SELECT body FROM character_addenda WHERE person_id IS ? AND archived=0 ORDER BY id DESC LIMIT 1",
            (person_id,),
        ).fetchone()
        return row["body"].strip() if row else ""
    except Exception:
        return ""


def _person_name(conn, person_id: int | None) -> str:
    if person_id is None:
        return "Teo"
    row = conn.execute("SELECT name FROM persons WHERE id=?", (person_id,)).fetchone()
    return row["name"] if row else "this person"


def _recent_interactions(conn, person_id: int | None, n: int = 10) -> str:
    rows = conn.execute(
        """SELECT text, created_at FROM memories
           WHERE source='chat' ORDER BY id DESC LIMIT ?""",
        (n,),
    ).fetchall()
    if not rows:
        return "(no recent interactions)"
    return "\n".join(f"- {r['text'][:150]}" for r in reversed(rows))


def _trait_state(conn) -> str:
    rows = conn.execute(
        "SELECT name, weight, gen_level FROM identity_traits WHERE status NOT IN ('archived') ORDER BY weight DESC LIMIT 6"
    ).fetchall()
    if not rows:
        return "(no traits yet)"
    return "\n".join(f"- {r['name']} (weight={r['weight']:.2f}, gen={r['gen_level']})" for r in rows)
